version: "3.9"
   
services:
  web:
    build:
      context: .
      target: development
    command: baseplate-serve --bind 0.0.0.0:9090 --debug --reload /src/configs/development.ini
    volumes:
      - .:/src
    ports:
      - "9090:9090"
